# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: babitajoshi299/simple-java-maven-app/.github/workflows/reusable.yml@master
    - uses: actions/checkout@v4
      # This step references the directory that contains the action.
    - uses: babitajoshi299/simple-java-maven-app/.github/actions/print_env_var@master

    #steps:
   # - uses: babitajoshi299/simple-java-maven-app/.github/actions/print_env_var/action.yml@master
