# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on:
  push:
  #  branches: [ "master" ]
  #pull_request:
   # branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2.2.3
      with:
            name: Jars
            path: /home/runner/work/java-junit-template-project/java-junit-template-project/lib/org.jacoco.ant-0.8.7.jar!/org/jacoco/ant/antlib.xml 
            
    - name: action being called here 
      uses: babitajoshi299/simple-java-maven-app/.github/actions/print_env_var@master   
    #- uses: babitajoshi299/simple-java-maven-app/.github/actions/print_env_var/action.yml@master
